const express = require('express')
const app = express()
const cors = require('cors')
const mongoose = require('mongoose')
const blogsRouter = require("./controllers/blogs")
const usersRouter = require("./controllers/users")
const config = require("./utils/config")
const logger = require("./utils/logger")
const loginRouter = require('./controllers/login')
const tokenExtractor = require("./middleware/token")
const errorHandler = require("./middleware/errorHandler")
const infoLogger = require("./middleware/infoLogger")
const userExtractor = require("./middleware/userExtractor")

mongoose.connect(config.MONGODB_URI)
        .then(() => logger.info(`Connected to MongoDB`))
        .catch((error) => {
          logger.error('error connecting to MongoDB:', error.message)
        })

app.use(cors())
app.use(express.json())
app.use(infoLogger)
app.use('/api/login/', loginRouter)
app.use('/api/users/', usersRouter)
app.use(tokenExtractor)
app.use(userExtractor)
app.use("/api/blogs/", blogsRouter)
app.use(errorHandler)

module.exports = app