DELETE http://localhost:3001/api/blogs/62ee04b1d11bc7f497ec0b2d
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hcmNvMTkwMCIsImlkIjoiNjJlYmFkN2MzNmFmOGE4MzliZDBiNDFiIiwiaWF0IjoxNjU5NzY0OTg3fQ.9PYKBSQ7cRVk81r1VQZo3yQBrXEkfIC9I58DqrmF3E0
